#!/usr/bin/python3
# import x from x1 as string

i = int(0)
alphabt = "abcdefghijklmnopqrstuvwxyz"
e = alphabt[5]
q = alphabt[17]
print(e)
# alphabt[i]
for i in alphabt:
    if alphabt[int(i)] != e | alphabt[int(i)] != q:
        print (alphabt[i]), end="")
